global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-server:8080']

  - job_name: 'chat-server-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-server-1:8081']

  - job_name: 'chat-server-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat-server-2:8082']

  - job_name: 'presence-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['presence-server:8083']

  - job_name: 'notification-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-server:8084']
